### ISSUE TITLE
store_attr() got an unexpected keyword argument 'names'

### ISSUE THREAD

**Issue by kouohhashi** [ohmeow/ohmeow_website#13]
Hi,
Thanks for great demo.

BTW, when i tried to go through the notebook, I got error at `hf_batch_tfm = HF_SummarizationBatchTransform(hf_arch, hf_tokenizer)` .

<img width="1146" alt="Screen Shot 2020-09-19 at 2 31 22 PM" src="https://user-images.githubusercontent.com/5446294/93659929-02099c00-fa85-11ea-8b23-f2fcea7522b9.png">
<img width="1156" alt="Screen Shot 2020-09-19 at 2 31 34 PM" src="https://user-images.githubusercontent.com/5446294/93659933-08981380-fa85-11ea-890d-f0268581475a.png">

Error said `store_attr() got an unexpected keyword argument 'names'`

Is this because of my fastai2 version?

My fastai version: 2.0.6
My transformers version: 3.1.0

**Comment by ohmeow** [comment]
It may be more so your fastcore version. See the docs on `store_attr` [here](https://fastcore.fast.ai/utils.html#store_attr).

fastai should ensure the correct version of fastcore is being reference, so perhaps try upgrading to the latest fastai and see if that resolves the issue.  Lmk.

**Comment by kouohhashi** [comment]
Thanks. you are right.
After upgrading fastcore, it worked!
