### ISSUE TITLE
Error in Summarization notebook

### ISSUE THREAD

**Issue by jsjaskaran** [ohmeow/ohmeow_website#16]
Hello

I'm running summary notebook on Google Colab but it throws the following error

`NameError: name 'HF_SummarizationBatchTransform' is not defined`

Could you please help with this.

Thanks

**Comment by ohmeow** [comment]
Yah, there was a breaking change in fastai 2.1.5 ... working on updating
the docs and then the summarization example. I'll follow up to this thread
when all is up :)

**Comment by ohmeow** [comment]
Done.

https://ohmeow.com/posts/2020/05/23/text-generation-with-blurr.html ... or you can call it from the huggingface docs.

**Comment by jsjaskaran** [comment]
Thanks for such a fast work.
I'll check and update here.

Thanks again.
