### ISSUE TITLE
Cannot import blurr

### ISSUE THREAD

**Issue by bui-thanh-lam** [ohmeow/ohmeow_website#17]
I've encountered this problem when using blurr in colab:
![image](https://user-images.githubusercontent.com/47263060/101587592-1cfe0380-3a17-11eb-8368-e1c3057fe234.png)
I think blurr needs updating to lastest pandas version.

**Comment by ohmeow** [comment]
Just updated everything to work with the latest fastai and transformers bits ... lmk if it works.

**Comment by bui-thanh-lam** [comment]
Yes, it's now working! Thanks!
