### ISSUE TITLE
A small question.

### ISSUE THREAD

**Issue by ShoubhikBanerjee** [ohmeow/ohmeow_website#8]
Thanx for your awesome works, I just wanted to know to know that your colab : [2020-05-23-text-generation-with-blurr.ipynb](https://github.com/ohmeow/ohmeow_website/blob/master/_notebooks/2020-05-23-text-generation-with-blurr.ipynb), is it fine tune or pre-training?

**Comment by ohmeow** [comment]
fine-tuning

I don't have the compute resources to pre-train BART (or most of the other big transformer models) from scratch and so most of my work is really focused on transfer learning and fine-tuning pre-trained models on custom datasets.

**Comment by ShoubhikBanerjee** [comment]
Thanx for your reply.
